interface Car {
  id: string;
  title: string;
  brand: string;
  model: string;
  year: number;
  price: number;
  currency: string;
  type: string;
  fuel_type: string;
  transmission: string;
  seats: number;
  mileage: number;
  location: string;
  description: string;
  features: string[];
  image_url: string;
  contact_phone: string;
  contact_whatsapp: string;
  featured: boolean;
  available: boolean;
}
 import a from "@/assets/aaa.jpeg";
 import a1 from "@/assets/aaa1.jpeg";
 import a2 from "@/assets/aaa2.jpeg";
 import a3 from "@/assets/aaa3.jpeg";
import a5 from "@/assets/a5.jpeg";
 import a4 from "@/assets/a4.jpeg";
 import a7 from "@/assets/a7.png";
 import a9 from "@/assets/a9.png";
 import a10 from "@/assets/a10.png";
 import a6 from "@/assets/a6.jpeg";
 import aaa from "@/assets/aaa.jpeg";
 import aaa1 from "@/assets/aaa1.jpeg";
 import aaa2 from "@/assets/aaa2.jpeg";
 import aaa3 from "@/assets/aaa3.jpeg";
 import a8 from "@/assets/a8.jpeg";
export const localCars: Car[] = [
  {
    id: "hot-1",
    title: "Hot Deal - Hyundai Sonata 2020",
    brand: "Hyundai",
    model: "Sonata",
    year: 2020,
    price: 18500000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: 45000,
    location: "Kigali",
    description: "Well-maintained Hyundai Sonata with excellent fuel efficiency. Clean interior and exterior.",
    features: ["Air Conditioning", "Power Steering", "Electric Windows", "Bluetooth"],
    image_url: a,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: true,
    available: true,
  },
  {
    id: "hot-2",
    title: "Hot Deal - Toyota RAV4 2019",
    brand: "Toyota",
    model: "RAV4",
    year: 2019,
    price: 22000000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: 38000,
    location: "Kigali",
    description: "Spacious RAV4 perfect for family trips and business use. Excellent condition.",
    features: ["4WD", "Air Conditioning", "Power Steering", "Alloy Wheels"],
    image_url: a6,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: true,
    available: true,
  },
  {
    id: "hot-3",
    title: "Hot Deal - Toyota Prado 2018",
    brand: "Toyota",
    model: "Prado",
    year: 2018,
    price: 35000000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Diesel",
    transmission: "Automatic",
    seats: 7,
    mileage: 52000,
    location: "Kigali",
    description: "Premium Toyota Prado with advanced safety features and luxury interior.",
    features: ["4WD", "Leather Seats", "Sunroof", "Navigation System"],
    image_url: a8, 
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: true,
    available: true,
  },

  {
    id: "cert-1",
    title: "Hot Deal - Hyundai ix35 2016",
    brand: "Hyundai",
    model: "ix35",
    year: 2016,
    price: 15500000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Petrol",
    transmission: "Manual",
    seats: 5,
    mileage: 78000,
    location: "Kigali",
    description: "Imodoka zigenzuwe & zifite ibyangombwa. Fully inspected and Hot Deal vehicle.",
    features: ["Air Conditioning", "Power Steering", "USB Port", "ABS"],
    image_url: a4,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
  {
    id: "cert-2",
    title: "Hot Deal - Toyota Noah 2015",
    brand: "Toyota",
    model: "Noah",
    year: 2015,
    price: 16800000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 8,
    mileage: 85000,
    location: "Kigali",
    description: "Hot Deal family van with spacious interior. Perfect for large families.",
    features: ["8 Seater", "Air Conditioning", "Electric Doors", "DVD Player"],
    image_url: a1,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },

  {
    id: "used-1",
    title: "Toyota Prius Hybrid 2017",
    brand: "Toyota",
    model: "Prius",
    year: 2017,
    price: 14500000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    mileage: 65000,
    location: "Kigali",
    description: "Eco-friendly hybrid vehicle with excellent fuel economy.",
    features: ["Hybrid Engine", "Air Conditioning", "Navigation", "Backup Camera"],
    image_url: aaa1,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
  {
    id: "used-2",
    title: "Toyota Prius 2016",
    brand: "Toyota",
    model: "Prius",
    year: 2016,
    price: 13800000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    mileage: 72000,
    location: "Kigali",
    description: "Reliable hybrid vehicle in excellent condition.",
    features: ["Hybrid Engine", "Bluetooth", "USB Port"],
    image_url: aaa3,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
  {
    id: "used-3",
    title: "Hyundai Sonata Hybrid 2018",
    brand: "Hyundai",
    model: "Sonata",
    year: 2018,
    price: 17200000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Hybrid",
    transmission: "Automatic",
    seats: 5,
    mileage: 48000,
    location: "Kigali",
    description: "Modern hybrid sedan with advanced features.",
    features: ["Hybrid Engine", "Leather Seats", "Sunroof", "Navigation"],
    image_url: aaa2,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
  {
    id: "used-4",
    title: "Kia K5 2019",
    brand: "Kia",
    model: "K5",
    year: 2019,
    price: 19500000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: 42000,
    location: "Kigali",
    description: "Stylish and modern sedan in pristine condition.",
    features: ["Air Conditioning", "Power Steering", "Alloy Wheels", "Bluetooth"],
    image_url: aaa,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
  {
    id: "used-5",
    title: "Kia Optima 2017",
    brand: "Kia",
    model: "Optima",
    year: 2017,
    price: 16800000,
    currency: "RWF",
    type: "sale",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: 55000,
    location: "Kigali",
    description: "Well-maintained Kia Optima with custom wheels.",
    features: ["Custom Wheels", "Air Conditioning", "Power Steering", "Electric Windows"],
    image_url: a5,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },

  // --- Hot Deal Cars ---
  {
    id: "rent-1",
    title: "Hot Deal - Toyota RAV4 2020",
    brand: "Toyota",
    model: "RAV4",
    year: 2020,
    price: 25000,
    currency: "RWF",
    type: "rent",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: 35000,
    location: "Kigali",
    description: "Perfect for city driving and weekend trips.",
    features: ["4WD", "GPS", "Air Conditioning", "Bluetooth"],
    image_url: a2,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
  {
    id: "rent-2",
    title: "Hot Deal - Hyundai Sonata 2019",
    brand: "Hyundai",
    model: "Sonata",
    year: 2019,
    price: 20000,
    currency: "RWF",
    type: "rent",
    fuel_type: "Petrol",
    transmission: "Automatic",
    seats: 5,
    mileage: 40000,
    location: "Kigali",
    description: "Comfortable sedan for business and leisure.",
    features: ["Air Conditioning", "Power Steering", "Bluetooth", "USB Port"],
    image_url: a3,
    contact_phone: "+250796684401",
    contact_whatsapp: "250796684401",
    featured: false,
    available: true,
  },
];