// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rldvhixtvjcpwoavdklz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZHZoaXh0dmpjcHdvYXZka2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTkxMzEsImV4cCI6MjA2OTI3NTEzMX0.YdZ9spmz1e2j-Dz4xipIalZsi8IJc-iUNSu62WvJFwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});